### ISSUE TITLE
新版2.8.2固件问题

### ISSUE THREAD

**Issue by wyb4112** [solosky/pixl.js#105]
新版固件用固件内自带数据刷塞尔达王国之泪,可以自动随机ID刷出来.
但是用之前传输进FLASH的数据.会出现第一次可以刷.后面游戏道具刷不出来但是pixl上显示的随即ID在不断变更.

**Comment by ca1e** [comment]
仅根据你的描述不能确定是固件问题，请先自行排查问题

**Comment by wyb4112** [comment]
所有数据在2.7.0都是正常刷的,试过了lcd和oled一样的问题
