### ISSUE TITLE
amiibo数据库使用搜索功能并选择amiibo后退出会导致重启

### ISSUE THREAD

**Issue by James-Makoto** [solosky/pixl.js#107]
复现流程：amiibo数据库>搜索>输入metroid>选则任一amiibo>按一下按键并选择退出
必定会导致机器重启。

**Comment by James-Makoto** [comment]
似乎是在输入关键词的时候超过3个字符会出现这个情况

**Comment by solosky** [comment]
closed due to duplicated with #116.
