### ISSUE TITLE
Crash when accessing the emulator menu after having used the database

### ISSUE THREAD

**Issue by DanTheMan827** [solosky/pixl.js#116]
Firmware v2.8.4

Accessing the emulator menu results in a crash if the database menu was previously accessed.

https://github.com/solosky/pixl.js/assets/790119/e441b5ee-a973-433b-a682-2129d1ee3e18

**Comment by solosky** [comment]
Hi , I am also noticed this bug , it can be reproduced by my device.

This issue seems related to memory allocation issue, maybe some memory region is corrupted. It’s kind of hard to address this issue.

Thank you report the issue, I will continue working on this.

**Comment by impeeza** [comment]
@solosky and @DanTheMan827 Sorry for beeing that guy, but on my device (allmiibo) with FW 2.8.5 this error still happen.

Even just now learning and playing with the "Amiibo Database" after a while on it when selecting the "Exit"  the device restarted also.

**Comment by solosky** [comment]
I will let the issue opened, and I still cannot figure out how to fix the issue...

**Comment by jumkey** [comment]
@solosky 我之前测试了下 把tlsf_free 换成普通的free就不会崩。好像是clear favlist的时候调用了free

**Comment by solosky** [comment]
Hi everyone,  

I think I finally fixed this issue, would you please have a try the fix version: https://github.com/solosky/pixl.js/actions/runs/6911499606

**Comment by impeeza** [comment]
wow will tried just now and worked great.
