### ISSUE TITLE
Backup Current Firmware / Files

### ISSUE THREAD

**Issue by impeeza** [solosky/pixl.js#119]
Hello there, I just Acquire a pre-made kit named «allmiibo» as far I can see is highly based on the original Pixl.js hardware, as far I can see it have a "modified" 2.6.2 firmware and is on English language.

Actually the device shows the next on System Settings -> Version
```
Version [2.6.2]
BuildDate [2023-07-2
GitHash [0783e4d]
Branch [main]
Target [0]
Dirty [1]
```
I want to install newer pixl.js firmware on it but thinking what the firmware and hardware could be very different from the original design, I like to have a backup of the current status of the device in order to be able to return to a well know working state.

How can this be achieved?

Thanks a lot for all your help.

**Comment by impeeza** [comment]
Thanks a lot for the quick response.

Perfect, the upgrade process seems straightforward, but I really like to have a copy of the actual firmware in case something goes wrong I will be able to go back to the actual state.

Regards.

**Comment by impeeza** [comment]
Hello there, I just updated the firmware to 2.8.4, and works fine, testing all features and so far working well, The only issue is what now all description tags of all amiibos are on Chinese, even if the language settings are on English, on the original firmware all descriptions was on English.

Thanks a lot for your responses and help.

**Comment by solosky** [comment]
Hi, the language of tag description should be English if you choose English in setting menu.
Would you please to post more information, like screenshot to let me have better understanding the issue?

**Comment by impeeza** [comment]
Hello there, I think I get confused myself, lets try to unravel my mind :P 

My settings are like this:
![image](https://github.com/solosky/pixl.js/assets/41979604/0755ca5a-04f3-4f72-bd60-8f22b65c5652)

so If I go Main Menu -> amiibo Emulator
![image](https://github.com/solosky/pixl.js/assets/41979604/80c1ca5d-783e-461c-995c-faac6d094e81)
I got into a "File Explorer", entering on the "amiibo" folder
![image](https://github.com/solosky/pixl.js/assets/41979604/ec376739-792f-407a-83c9-ef5607c7db91)
and then into other folder:
![image](https://github.com/solosky/pixl.js/assets/41979604/bb964df9-9bcb-4936-bdcd-20c173c40b01)
I can select a amiibo bin file:
![image](https://github.com/solosky/pixl.js/assets/41979604/8d0e063b-f798-4118-bdc1-2713bf2734d6)
And for that amiibo the description tag is on English:
![image](https://github.com/solosky/pixl.js/assets/41979604/495106c7-c573-4f24-a45f-d8f6120f8b40)

but if I go to amiiboLik folder and select one of the files on that folder
![image](https://github.com/solosky/pixl.js/assets/41979604/b4937b94-f32e-49dd-9f8e-e6b6deb568e9)
![image](https://github.com/solosky/pixl.js/assets/41979604/377be3b5-2572-4244-ab0b-a3e26c7c8e1c)
The details of that file are on Chinese:
![image](https://github.com/solosky/pixl.js/assets/41979604/0baad1f1-ff58-4509-bcaf-b40e944f9e92)


Also if on the Main Menu I go to AmiiboLink
![image](https://github.com/solosky/pixl.js/assets/41979604/fb22a9e8-0dd3-4925-942d-0eff37a0572b)

And then Select one of the files:
![image](https://github.com/solosky/pixl.js/assets/41979604/907baa3e-e127-4492-b41f-dd10bfd3c71f)

The Tag details also are on Chinese:
![image](https://github.com/solosky/pixl.js/assets/41979604/f91606cf-ac8f-4614-94e9-068237a8d379)

therefore, seems is a problem with the files on the AmiiboLink folder, the ones transferred by the AmiLoop app.

**Comment by solosky** [comment]
Hi, interesting findings, I will try it later, because I don't have device on hand now. 

BTW, you can try the Amiibo Database app, it contains almost all released amiibo information, and generate amiibo data on the fly. Also, it has more detail description for Zelda game series amiibos.

**Comment by impeeza** [comment]
Hello there, I just downloaded and install on my android phone the Umiibo app, and transfer some bin files on AmiiboLink mode and the descriptions are on chinesse :(

The Amiibo Database App is Umiibo?

**Comment by solosky** [comment]
No, I mean the app in Pixl.js. 

![image](https://github.com/solosky/pixl.js/assets/480111/d7288d34-a282-4cef-b48d-d12a30f8c20d)

**Comment by solosky** [comment]
Hi, I confirmed it's a bug. 
The tag description did not honor the language settings.
I will release a new version later today to fix this issue.

Thank your report on this.

**Comment by solosky** [comment]
Hi, there, please update firmware to 2.8.5 to fix this name issue.

**Comment by impeeza** [comment]
@solosky sorry for ping a closed issue, I still have the doubt about the " Amiibo Database app" you mentioned on a message above.  which one is that app?  thanks.

**Comment by impeeza** [comment]
> No, I mean the app in Pixl.js.
> 
> ![image](https://user-images.githubusercontent.com/480111/276864480-d7288d34-a282-4cef-b48d-d12a30f8c20d.png)

Thanks, learing about that section, great addition to the device.

**Comment by wouter-luimes** [comment]
> Thanks a lot for the quick response.
> 
> Perfect, the upgrade process seems straightforward, but I really like to have a copy of the actual firmware in case something goes wrong I will be able to go back to the actual state.
> 
> Regards.

Sorry to bother you, but were you able to obtain a copy of the firmware that originally came with the device in the end? And if so, would you be able to share it? I have this same device myself and also would like to have a back-up just in case.

**Comment by impeeza** [comment]
> > Thanks a lot for the quick response.
> > Perfect, the upgrade process seems straightforward, but I really like to have a copy of the actual firmware in case something goes wrong I will be able to go back to the actual state.
> > Regards.
> 
> Sorry to bother you, but were you able to obtain a copy of the firmware that originally came with the device in the end? And if so, would you be able to share it? I have this same device myself and also would like to have a back-up just in case.

No, I was unable but never needed, the device works very well with 2.8.6 firmware and the improvement are welcomed.
