### ISSUE TITLE
Read Amiibos

### ISSUE THREAD

**Issue by impeeza** [solosky/pixl.js#120]
Hello there, Are you planning to implement the function of reading an actual Amiibo and dumping it in to a bin file?

Thanks.

**Comment by solosky** [comment]
It's not possible. Currently hardware only supports 14a card emulation (Like Ntag21x, Mifare, Desfire), cannot act as reader to read amiibo tags.

**Comment by impeeza** [comment]
Cool, Thanks for the quick response.
