### ISSUE TITLE
Add Reboot/Restart option

### ISSUE THREAD

**Issue by impeeza** [solosky/pixl.js#124]
Hello there, on some cases like when you restore your settings.bin file from a backup using Web Interface could be nice to have an option under Settings.. to reboot/restart the device and the new settings.bin get read.

Thanks for your work.

**Comment by solosky** [comment]
suggestion accepted, I will add this function in next minior release.

**Comment by impeeza** [comment]
Just tested an works very nice.  the only change I propose is on the new `es_CO.c` file the line
`    [_L_APP_SET_REBOOT] = "Reiniciar el sistema",`

be changed for:

`    [_L_APP_SET_REBOOT] = "Reiniciar",`

Is neat and doesn't change the meaning.

Thanks for the great work.
