### ISSUE TITLE
some amiibo is not sending over to my allmiibo zero

### ISSUE THREAD

**Issue by BladeTechBlade** [solosky/pixl.js#135]
At the moment I am sending a few amiibos at a time But for the animal crossings are not being Uploaded because it keeps saying error on some off them.

**Comment by solosky** [comment]
Please provide details on how to reproduce this issue. 
short video/images are welcome to post here to let me know what issue are you facing.

**Comment by BladeTechBlade** [comment]
I got it working it seems that the device does not like long names and having the same name that folder was in like Animal Crossing x Sanrio Series and I had to short it to sanrio.

**Comment by impeeza** [comment]
Can to give us a example of your names to try to control that on the firmware
