### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by nmra1999** [solosky/pixl.js#147]
Hi, i really like the project and i would like to contribute with a Portuguese Translation for the Pixl device and webpage, i saw some of the @impeeza posts here, but i'm not familiar with coding or the github itself, is it possible someone could provide me the main files (in english or spanish), so i could open them in notepad or something similiar to translate them? Also portuguese uses a lot of special characters like spanish so how could i set it to be UTF-8

Thanks in advance

**Comment by impeeza** [comment]
You can help to the project, the new translation method is described on:
https://github.com/solosky/pixl.js/blob/develop/fw/docs/translation.md

**Comment by impeeza** [comment]
Yeah you need to run the scripts and edit some files, if you like share with us the i18n.csv file and I will try to generate all needed files.

**Comment by Ender519** [comment]
I contributed Portuguese alongside a few other languages included in the latest pull with @impeeza's help.  Therefore, I think this issue can be marked resolved.

**Comment by NaomiRedPanda** [comment]
Hey can you add the Portuguese (Portugal) language differentiation? It
would mean a lot to be added as well...Thanks :)

A terça, 19/12/2023, 4:15 PM, Ender519 ***@***.***> escreveu:

**Comment by impeeza** [comment]
Yes, it can be done, the current language is pt_BR we can add pt_PT, just send us the i18n.csv with the strings, or you can do it yourself following https://github.com/solosky/pixl.js/blob/main/docs/en/05%2B5-translation.md instructions.

**Comment by impeeza** [comment]
Sorry for being late, the https://github.com/solosky/pixl.js/pull/189 was created.  tested on my device and works fine.

**Comment by solosky** [comment]
Released in 2.9.2.
