### ISSUE TITLE
fw_update.bat translation

### ISSUE THREAD

**Issue by impeeza** [solosky/pixl.js#149]
Hello there, I am attaching a copy of the file `fw/scripts/fw_update.bat` translated to English, I am not creating a PR because I do prefer you take the option of include and name it as better suits to the code
[fw_update_EN.zip](https://github.com/solosky/pixl.js/files/13434946/fw_update_EN.zip)

**Comment by solosky** [comment]
Okay, I think it would better if Chinese and English are supported in one bat file, I will combine your translation to a single one bat file.

**Comment by impeeza** [comment]
Great Idea. I hope the file be helpful. closing this Issue.

**Comment by solosky** [comment]
Hi, I have updated the fw_update.bat  using your translation version, thanks.
