### ISSUE TITLE
Wrong alignment on some options of menu items 

### ISSUE THREAD

**Issue by impeeza** [solosky/pixl.js#164]
For the sub-menu: Amiibo Database -> Tag Details, the options
* Auto Rand.
* Show QR
The current option shown between [ON/OFF] is not right aligned
![image](https://github.com/solosky/pixl.js/assets/41979604/55d4e7b1-7ac9-47c8-9ec6-4e550533d6c3)

For the sub-menu: amiiboLink -> amiibo Details, the options
* Mode
* Random auto.
* Compati. Mode
 
The current setting [ON/OFF] is not right aligned
![image](https://github.com/solosky/pixl.js/assets/41979604/a8c42994-8584-40b7-a332-963f83c0a284)

**Comment by solosky** [comment]
Yeah, you are right, I have introduce a new format for list view, but I haven't updated other senarios, I think I will update them in furture commits.

**Comment by solosky** [comment]
Fixed in develop branch.

**Comment by impeeza** [comment]
Thank you so much.
