### ISSUE TITLE
屏幕亮度调节

### ISSUE THREAD

**Issue by hitlcl** [solosky/pixl.js#18]
屏幕感觉稍微有点亮，能否增加亮度调节功能

**Comment by solosky** [comment]
可以安排。

不过这个功能只能使用PWM调光，比较伤眼，而且用纽扣电池开背光就特别耗电，可以增加背光的限流电阻来达到减少亮度的功能。

**Comment by hitlcl** [comment]
> 可以安排。
> 
> 不过这个功能只能使用PWM调光，比较伤眼，而且用纽扣电池开背光就特别耗电，可以增加背光的限流电阻来达到减少亮度的功能。

频率拉高点，应该还行

**Comment by hitlcl** [comment]
限流电阻改成1k以后感觉亮度正好，用不着调亮度了
