### ISSUE TITLE
没有打开LiPo锂电池选项，右上角一直显示的是满电，用户不知到要充电，电池过放后，导致无法充电进去。希望默认打开LiPo锂电池选项

### ISSUE THREAD

**Issue by strengthen** [solosky/pixl.js#182]
没有打开LiPo锂电池选项，
右上角一直显示的是满电，
用户不知到要充电，
电池过放后，
导致无法充电进去。
希望默认打开LiPo锂电池选项，
或者没有打开LiPo锂电池选项，右上角也可以看到电量。

**Comment by impeeza** [comment]
Seems the default settings.bin file shipped on the OLED devices have no the LiPo option enabled by default the user can go and change manually, and then restart the device and the battery level is now updated correctly

**Comment by solosky** [comment]
Released in 2.9.2.
