### ISSUE TITLE
Is there a way to donate money to this project or author?

### ISSUE THREAD

**Issue by fishybow** [solosky/pixl.js#187]
Is there a way to donate money to this project or author?

**Comment by solosky** [comment]
Hi sir, 
Thank you for your kind intentions!
I don't have any channel to receive donation yet and this project does not need donation currently. 

Meanwhile, I would like that more people could make their contribution on the firmware deployment.

**Comment by fishybow** [comment]
Cool. I will continue contributing to the project. Meanwhile, if you have a donation channel setup, please let me know.
