### ISSUE TITLE
关于息屏缓存记录当前状态信息

### ISSUE THREAD

**Issue by skytotwo** [solosky/pixl.js#19]
现在息屏后之前所有操作都无法记录，可否息屏后记录当前所在页面、当前是否亮屏等信息。
亮屏后预读此信息

**Comment by solosky** [comment]
这个后面看情况能否实现。

目前在不用的情况是完全关机来减少电池消耗，考虑到是纽扣电池，使用时间是需要优先考虑的。

**Comment by skytotwo** [comment]
嗯那是否可以flash中放个init文件，用来保存配置信息，关机写入，开机读取，这样也不用长待机，也不用写缓存到芯片里

**Comment by solosky** [comment]
这个比你想象的要复杂，断电后恢复之前的运行状态很难，除非不休眠，但是休眠会导致功耗增加，这需要一个平衡。
暂时不考虑这个功能。 

后面会增加一个调节超时等待的时长的功能，可以自行调节超时时长。
