### ISSUE TITLE
German language file

### ISSUE THREAD

**Issue by Ulfenknulfen** [solosky/pixl.js#191]
thers a small problem in german laguage file:

"AUF" war wrong - it must be: "AUS"

problem fixed in attached file.
Please use it

thx
Paddy
[de_DE.zip](https://github.com/solosky/pixl.js/files/13891009/de_DE.zip)

**Comment by impeeza** [comment]
The https://github.com/solosky/pixl.js/pull/192 is created using this file.

**Comment by solosky** [comment]
Rleased in 2.9.3 
Thanks for your contribution!
