### ISSUE TITLE
Bug after updating to 2.9.3

### ISSUE THREAD

**Issue by Brickleberry19** [solosky/pixl.js#197]
After I updated to version 2.9.3 it looks like this for me 
https://github.com/solosky/pixl.js/assets/115247704/858ca35b-c4f1-40b0-850b-3f76c2afe586

(OLED version Updated With nRF Connect on Android)

**Comment by solosky** [comment]
May I know where did you download the firmware ? do you download the firmware from github release page?
I tested the release version from github release page,  no issue was found.

**Comment by Brickleberry19** [comment]
Yes i Download it from your GitHub Release page

**Comment by solosky** [comment]
Hi @Brickleberry19, sorry, I think I have fixed this issue in 2.9.4, please upgrade to 2.9.4  https://github.com/solosky/pixl.js/releases/tag/2.9.4 

Thanks for your reporting this issue.

**Comment by Brickleberry19** [comment]
Thanks for the quick fix, it works

**Comment by solosky** [comment]
you are welcome
