### ISSUE TITLE
Open up more RFID / NFC slots

### ISSUE THREAD

**Issue by fishybow** [solosky/pixl.js#203]
The card emulator has 8 slots max right now. Are there any concerns to open that up to more slots?

**Comment by solosky** [comment]
Yes, if we change more card slots, slotConfig may consume to much mem and slower initiation for emulation.

But we may increase to a larger number like 64 slots as maximum slots allowed.  User can choose any number bellow 64 to be his own slot count.

**Comment by fishybow** [comment]
That makes sense. We can keep 2 slots open by default but allow users to turn on a maximum of 64.

**Comment by fishybow** [comment]
I looked at the code, it seems that the count 8 is defined by within a dependency library. There is no straight forward way to modify that. I'm closing this issue for now.
