### ISSUE TITLE
一个文件删除问题

### ISSUE THREAD

**Issue by tlxxl** [solosky/pixl.js#219]
遇到一个情形误传一个文件名比较长的文件后无法将其删除 网页端删除后一刷新依旧存在，设备端删除无法按下ok 也无法改名

问题演示：https://github.com/solosky/pixl.js/assets/91904997/48f82de3-7747-41c4-aa75-87d21df95fd3
为方便复现，压缩上传了所用文件：[文件.zip](https://github.com/solosky/pixl.js/files/14478754/default.zip)

**Comment by solosky** [comment]
感谢反馈，这个是由于上传的时候没有校验文件名是否符合要求，最新的提交已经加上了校验，但是已经上传的文件无法删除，只能通过在设置菜单里面格式化磁盘解决。
