### ISSUE TITLE
The amiibo emulator, how to add information to your own amiibos?

### ISSUE THREAD

**Issue by Vorffeed** [solosky/pixl.js#222]
Any way to enter the amiibo description information as it appears in the database, but in the amiibo emulator, where you put your own amiibo backub so it doesn't come up underneath just what that amiibo's name is?

**Comment by impeeza** [comment]
You can edit the source and build for your self

https://github.com/solosky/pixl.js/tree/main/fw/data

**Comment by Vorffeed** [comment]
> You can edit the source and build for your self
> 
> https://github.com/solosky/pixl.js/tree/main/fw/data
But I don't see anything there that is for the amiibo emulator, I only see for the database.

**Comment by impeeza** [comment]
The emulator gets all data from the bin file and the name is read from database if ID of the bin file is on the database.

**Comment by Vorffeed** [comment]
Well, it doesn't do it to me as you can see ><
Database
![IMG_20240323_202845](https://github.com/solosky/pixl.js/assets/10000442/48dff2fe-888c-48df-b593-030914ef4823)
vs Amiibo Emulator
![IMG_20240323_202915](https://github.com/solosky/pixl.js/assets/10000442/893a4b54-3df6-4f5c-ad6e-50a96feca194)

**Comment by solosky** [comment]
Hi the note in Amiibo Emulator does not display note in Amiibo database,  but you can add your own note by web UI or iNFC APP.

**Comment by impeeza** [comment]
![image](https://github.com/solosky/pixl.js/assets/41979604/bf310452-95e7-4e1b-8a0d-7a4ad5c41ccf)
![image](https://github.com/solosky/pixl.js/assets/41979604/24edff5e-01cd-4910-be81-ec6a4bf4ae79)

![image](https://github.com/solosky/pixl.js/assets/41979604/6d4ee7ed-fb64-4b12-8a72-b5b0f7aec001)

**Comment by Vorffeed** [comment]
ok, thanks.
