### ISSUE TITLE
Why Hungarian (Hungary) 'hu_HU.c' file mentioned twice in 'fw/application/Makefile' ?

### ISSUE THREAD

**Issue by MayanKoyote** [solosky/pixl.js#229]
Why Hungarian (Hungary) 'hu_HU.c' file mentioned twice in 'fw/application/Makefile' ?
Lines [300](https://github.com/solosky/pixl.js/blob/9bf5fba7e89ebf0b7ab822cf498ada097bf735ec/fw/application/Makefile#L300) and [303](https://github.com/solosky/pixl.js/blob/9bf5fba7e89ebf0b7ab822cf498ada097bf735ec/fw/application/Makefile#L303).
Typo or something else?

**Comment by solosky** [comment]
Maybe it's a mistake... 
Anyway, I will correct them. 

Thanks.

**Comment by solosky** [comment]
fixed in https://github.com/solosky/pixl.js/commit/223609b07aa2b97a6adfeb8b2932985d1c4d3e64
