### ISSUE TITLE
More buttons?

### ISSUE THREAD

**Issue by JohnVeness** [solosky/pixl.js#233]
Hello. Many thanks for this project, it looks great.

Do you know what would be involved to add more hardware buttons to the design? At the moment there is up, down, and OK. It might be nice if there was a D-pad, and a button to go back as well as OK. A form factor a bit like the Dreamcast VMU would be great.
![image](https://github.com/solosky/pixl.js/assets/2512915/6f055781-5549-4fbf-9e55-25a309c32333)

**Comment by solosky** [comment]
No such plan to add more button, because current design is very compact and cannot put more buttons like your demostrated device. And also the controll logic requires be re-constructed if more buttons added, that will be a lot of work.
