### ISSUE TITLE
The 'amibo' application automatically adds two-dot ellipsis to (some) text lines.

### ISSUE THREAD

**Issue by MayanKoyote** [solosky/pixl.js#236]
For most menu item text lines, the ellipsis is specified in the localization file.
For example, like here:
https://github.com/solosky/pixl.js/blob/223609b07aa2b97a6adfeb8b2932985d1c4d3e64/fw/application/src/i18n/pt_PT.c#L71
But in two cases (same app, 'amiibo'), the application itself adds a two-dot ellipsis instead:
https://github.com/solosky/pixl.js/blob/223609b07aa2b97a6adfeb8b2932985d1c4d3e64/fw/application/src/app/amiibo/scene/amiibo_scene_file_browser_menu.c#L301
https://github.com/solosky/pixl.js/blob/223609b07aa2b97a6adfeb8b2932985d1c4d3e64/fw/application/src/app/amiibo/scene/amiibo_scene_file_browser_menu.c#L303

Is it possible to put this in a uniform order (i.e. the ellipsis is specified in the localization file)?

**Comment by solosky** [comment]
> I would vote for putting the ellipsis inside the i18n.csv to unify all text as much as possible. In addition to that, ellipsis are typically three, not two dots. I already started working on reworking the de_DE translation, so I could integrate this across the board.

aggreed.

**Comment by Schokobecher** [comment]
`_L_DELETE` is also used in the context of
https://github.com/solosky/pixl.js/blob/223609b07aa2b97a6adfeb8b2932985d1c4d3e64/fw/application/src/app/amiibo/scene/amiibo_scene_file_browser_menu.c#L258

Which would to look like this after swapping over the ellipsis to `i18n.csv`

> Delete... *FILENAME* ?

Is that acceptable? Or do we need another string in i18n.csv?

We also should be able to move the various question marks with something like this:

```c
snprintf(msg, sizeof(msg), "%s %s", getLangString(_L_DELETE), string_get_cstr(app->current_file));
```
```csv
_L_DELETE,Delete... %s ?
```
right?

**Comment by MayanKoyote** [comment]
Be that as it may, but something needs to be done about it.
