### ISSUE TITLE
The device does not want to show characters from the line [_L_APP_CHAMELEON_CARD_SET_NICK_FAILED] that are not Basic Latin.

### ISSUE THREAD

**Issue by MayanKoyote** [solosky/pixl.js#242]
en_US - line is 'Set Nick Failed!' and the message is displayed as expected: 'Set Nick Failed!':
![IMG_3466](https://github.com/solosky/pixl.js/assets/43220515/a151315a-e768-4459-80af-346fea27a7ef)

zh_Hans - line is '设置卡名失败' and the message displayed is ' '. Everything is missing, empty message:
![IMG_3470](https://github.com/solosky/pixl.js/assets/43220515/24a9d2cf-8d79-4eed-8436-518c98302f60)

fr_FR - line is 'Définir le Pseudo a Échoué!' and the message displayed is 'Dfinir le Pseudo a chou!'. All the characters 'é' and 'É' are missing:
![IMG_3474](https://github.com/solosky/pixl.js/assets/43220515/be1addf6-8ea3-4599-a2f8-694d759b2456)

ja_JP - line is 'ニックネームが設定できませんでした!' and the message displayed is '!'. Everything except the exclamation mark is missing:
![IMG_3481](https://github.com/solosky/pixl.js/assets/43220515/a2e9fa61-aa50-4a7d-9da8-3b715f7df787)

It seems that the app wants to display only Basic Latin characters and does not want to display any others.

A similar story is observed in the case involving [_L_APP_CHAMELEON_CARD_ADV_ID_EDIT_INVALID_INPUT] line.

**Comment by solosky** [comment]
Quickly checked, the mui_toast_view does not set wqy font before draw characters. 
I will fix this later today.

**Comment by solosky** [comment]
I should fix this issue, but it comes a new issue: The text is out of border when toast content displays more than one line.
I will fix that when I am avaliable.
