### ISSUE TITLE
Recursively upload directories

### ISSUE THREAD

**Issue by pjotrvdh** [solosky/pixl.js#255]
Is it possible to upload a directory tree?

I've been creating new folders and navigating in to them and upload the bin files manually into them.
I'd like to be able to select a directory on my computer and recursively upload directories and files.
is that possible and if so, how do I use this feature?

**Comment by solosky** [comment]
Possible, but I'd suggest to try Amiibo Database app, which has all amiibo data build-in with categorized into games. No need upload amiibo files to device.

**Comment by pjotrvdh** [comment]
Thank you for the advice. I've never looked beyond the uploaded amiibo's. The database function is great!
