### ISSUE TITLE
Adding a feature to Allmiibo (maybe) 

### ISSUE THREAD

**Issue by Splatboy0612** [solosky/pixl.js#256]
Hello, I'd like to give an Allmiibo feature idea: what if you add a "lock" feature that prevents you from generating random Amiibo ID on your saved Amiibos by accident, so you couldn't lose your Amiibo lvl in Smash for example

**Comment by Splatboy0612** [comment]
Maybe some people will find it useful

**Comment by solosky** [comment]
Added Read-only support for Amiibo Browser and Amiibo Database app.

**Comment by solosky** [comment]
Release in 2.11.0

**Comment by Splatboy0612** [comment]
Nice
