### ISSUE TITLE
Where do I get the firmware zip for allmiibo????

### ISSUE THREAD

**Issue by Breadmasterpro** [solosky/pixl.js#265]
I can not find the firmware zip package mentioned in 02-flash-firmware.md to update my allmiibo with web method. where is it!?!?

**Comment by solosky** [comment]
please download from release page. if you are going to use OTA to update firmware, unzip it and use xxx_ota.zip to upgrade.

**Comment by Breadmasterpro** [comment]
> please download from release page. if you are going to use OTA to update firmware, unzip it and use xxx_ota.zip to upgrade.

my appolagies, I cannot seem to find it! 

Is this it?
![image](https://github.com/user-attachments/assets/222be8f6-66be-43b8-9b54-0a45071c71f3)

**Comment by Breadmasterpro** [comment]
> please download from release page. if you are going to use OTA to update firmware, unzip it and use xxx_ota.zip to upgrade.

AHA! found it! thanks! 
![image](https://github.com/user-attachments/assets/19921868-ac84-4c52-9ef7-52a25ea08388)

**Comment by Breadmasterpro** [comment]
> please download from release page. if you are going to use OTA to update firmware, unzip it and use xxx_ota.zip to upgrade.

It Freezes at this point. does not move after 5 minutes. even after retrying.
![image](https://github.com/user-attachments/assets/086662eb-9e1a-40ea-bf3c-947ff0d82aad)

**Comment by Breadmasterpro** [comment]
now my allmiibo is stuck on 'DFU update waiting... ' HELP!

**Comment by Breadmasterpro** [comment]
WHEW I FIXED IT!!! yes!! new firmware is very cool! I fixed it by using the nrf connect app. all fixed thankyou!!!

**Comment by Breadmasterpro** [comment]
it keeps getting stuck on whitescreen...

**Comment by solosky** [comment]
Hi, just want to know, have you resolved your issue ?
