### ISSUE TITLE
Bootloop in the DFU Updater mode 

### ISSUE THREAD

**Issue by GlebDGT11** [solosky/pixl.js#266]
Hi, @solosky , I have recently catch problem for my allmiibo, that I bought on 2nd of July and getting it in 29th of July. So, the problem: When I wanted to download latest firmware to 2.11.0 from 2.10.2, firstly screen looking like it's getting hammered, but not, I quickly put it into DFU Updater to install that firmware again, and while updating is getting finished, it just stops at 240k firmware bytes and started bootlooping in the DFU Updater mode, and it won't able to return to Main Menu

Uploading VID_2024_08_27_16_45_14_1262661556606660999115.mp4…

**Comment by solosky** [comment]
Sorry, I cannot see the video you posted here. 
you can try upgrade firmware with MTools BLE and NRF Connect. 

https://github.com/solosky/pixl.js/blob/main/docs/en/02-Flash-Firmware.md#nRF-Connect-APP

**Comment by GlebDGT11** [comment]
I fix the problem, and it's now working, thanks to my friend that helped me out from this

**Comment by impeeza** [comment]
How did you solve the problem?   please close the issue if is solved.

**Comment by GlebDGT11** [comment]
I just short circuited some contacts on Allmiibo Board to reset the system and then writing the firmware again
