### ISSUE TITLE
Amiibo tags invalid

### ISSUE THREAD

**Issue by MeleeGamer** [solosky/pixl.js#269]
Regardless of the .Bin File or where I get it from, the device states that it is not an Amiibo and does not work. Can anyone help?

**Comment by impeeza** [comment]
Bin files are DUMPS of the original amiibo THEY ARE NINTENTO COPYRIGHTED MATERIAL, so ask for them is piracy and is against this site rules.

ONLY VALID bind files will work.   you must supply dumps of your legally acquired amiibo.

**Comment by impeeza** [comment]
please close this issue.

**Comment by solosky** [comment]
Please note the pixl.js only read as amiibo if the file size is 540 or 532.  
Please let me know what your amiibo file size is.
