### ISSUE TITLE
BUG: 2.11.1 new Amiibo wrong ID

### ISSUE THREAD

**Issue by t0mizwf26** [solosky/pixl.js#273]
According to AmiiboAPI https://github.com/N3evin/AmiiboAPI/issues/181

The IDs in PR#272 https://github.com/solosky/pixl.js/pull/272

> 0801000004360402,Callie - Alterna,小拟 - 幻界
> 08020 **2** 0004370402,Marie - Alterna,小萤 - 幻界
> 08030 **1** 0004380402,Pearl - Side Order,小姬 - 秩序篇
> 08040 **1** 0004390402,Marina - Side Order,饭田 - 秩序篇

are wrong. They are trying to re-verify the IDs ATM.

**Comment by AbandonedCart** [comment]
https://github.com/N3evin/AmiiboAPI/issues/181#issuecomment-2325174588 are valid.

**Comment by solosky** [comment]
Confirmed from users, the amiibo ids are correct.

**Comment by AbandonedCart** [comment]
> Confirmed from users, the amiibo ids are correct.

The set I posted are the official ones retrieved from retail statues. The set in the first post have a typo that circulated ahead of the release.

**Comment by solosky** [comment]
I just checked the Amiibo API data, you are correct, I think I will update the amiibo ID in next release to sync up with Amiibo API. 

Thanks.
