### ISSUE TITLE
Allmiibo screen randomy starts bugging out

### ISSUE THREAD

**Issue by Breadmasterpro** [solosky/pixl.js#274]
After updating to v2.11.0 the screen will sometimes go completely blank or bug out and go upside down. All the allmiibo functions still work when the screen goes blank and I can still scan and switch amiibo but I just can't see anything at all. The only way to fix this is to let it enter sleep mode then turn it on again.

https://github.com/user-attachments/assets/f10a9185-2c19-4424-a983-24fd577ae5cf

![20240824_214201](https://github.com/user-attachments/assets/4b3e0dd7-0c06-49a1-b7e6-bf3dbc759552)
![20240824_214201](https://github.com/user-attachments/assets/45362b02-69f2-4116-8291-1c0b9b5d9dd4)

**Comment by Breadmasterpro** [comment]
![Uploading 20240908_181004.jpg…]()

**Comment by Breadmasterpro** [comment]
![20240908_181004](https://github.com/user-attachments/assets/c20aca2f-f7e7-4de0-9586-9ef7e233d2b1)

**Comment by solosky** [comment]
This issue happens before, still can not know the reason, try to flash firmware again or reset the device by pull out the battery.

**Comment by Breadmasterpro** [comment]
> This issue happens before, still can not know the reason, try to flash firmware again or reset the device by pull out the battery.

Ok
