### ISSUE TITLE
新建标签时名称问题

### ISSUE THREAD

**Issue by hitlcl** [solosky/pixl.js#29]
目前版本在亮屏后第一次新建标签输入名称时默认光标在左上角，需要移动到ok键，创建时稍微有些繁琐。
是否可以默认光标在ok上（或者跳过名称输入直接创建empty.bin，反正最后标签名称也会自动改为amiibo的名称）

**Comment by solosky** [comment]
已修复，默认光标已经设置再OK按钮上。下一个版本发布
