### ISSUE TITLE
休眠保存之前的设置

### ISSUE THREAD

**Issue by matyml** [solosky/pixl.js#33]
修改pixl的休眠时间和背光开关状态，修改后的状态不能进行保存。好像只能保存上电第一次的修改状态。
例如上电后的第N次使用，把背光设置开修改为背光设置关，休眠时间从180s改为30s后，等待设备进入休眠后，再次打开设备后pixl还是未修改之前的设置(背光设置开，休眠时间180s)而不是最后一次休眠前修改的设置

**Comment by solosky** [comment]
目前是有个BUG，在设置界面停留至休眠没有保存设置，目前这个BUG已经修复，在下一个版本修复。
如果是离开设置页面设置就会立即保存，这个经过我的多次测试功能是正常的。
