### ISSUE TITLE
能否在Amiibo模拟器子菜单增加返回主菜单选项

### ISSUE THREAD

**Issue by hitlcl** [solosky/pixl.js#41]
现在只能通过长按->返回主菜单 的方式返回，稍微有点慢；能否像动画播放器一样直接增加返回主菜单的选项？

**Comment by solosky** [comment]
考虑到每屏最多只能显示5行汉字，如果再加一个返回主菜单，还有个上级目录返回菜单，首屏只展示3个文件，不打算加这个菜单了。

**Comment by hitlcl** [comment]
> 考虑到每屏最多只能显示5行汉字，如果再加一个返回主菜单，还有个上级目录返回菜单，首屏只展示3个文件，不打算加这个菜单了。
我的意思是在进入amiibo模拟器选项以后，在显示external flash那个菜单加个返回上一级（类似动画播放器那样）。

**Comment by hitlcl** [comment]
> 考虑到每屏最多只能显示5行汉字，如果再加一个返回主菜单，还有个上级目录返回菜单，首屏只展示3个文件，不打算加这个菜单了。

我的意思是在进入amiibo模拟器，显示external flash的那个菜单加个返回主菜单的选项（类似动画播放器那样），不是在文件列表那加

**Comment by solosky** [comment]
感谢建议，已经添加
