### ISSUE TITLE
文件夹重命名

### ISSUE THREAD

**Issue by matyml** [solosky/pixl.js#42]
文件夹重命名，在确认后网页会一直转圈，等个几十秒pixl会瞬间重启，文件夹名字也没改成功。

**Comment by solosky** [comment]
请详细描述下如何复现这个BUG

**Comment by solosky** [comment]
麻烦提供下文件夹完整的路径和要命名的文件夹名字，如果能提供文件夹里面的文件就最好了。

**Comment by solosky** [comment]
这个是因为测试版本开启了WDT，这个功能目前还有问题，正式版本会关闭掉。
