### ISSUE TITLE
重命名的amiibo在写入数据后会自己改名

### ISSUE THREAD

**Issue by hitlcl** [solosky/pixl.js#43]
网页端重命名的amiibo，在ns上写入数据（如：设置->amiibo->添加所有者昵称）后会自动改成amiibo本身的名称

**Comment by hitlcl** [comment]
感觉和创建空bin然后写入后改名是一个逻辑，不知道有没有必要修

**Comment by solosky** [comment]
麻烦详细描述下复现步骤，便于我测试和验证逻辑，谢谢

**Comment by solosky** [comment]
麻烦详细描述下复现步骤，便于我测试和验证逻辑，谢谢

**Comment by hitlcl** [comment]
> 麻烦详细描述下复现步骤，便于我测试和验证逻辑，谢谢

固件版本2.3.1.
1、网页任选一个bin文件，重命名为test.bin
2、打开ns，点击设置->amiibo->添加所有者和昵称
3、pixl选择test.bin，然后用ns读取
4、ns读取后设置所有者和昵称，提示放置amiibo后放置pixl，ns对pixl进行写入后test.bin会自动改名为ammibo本身的名称，例如Isabelle.bin

**Comment by solosky** [comment]
目前修改了仅在文件名是默认的new.bin名字才改名。
