### ISSUE TITLE
读取文件失败且网页无法打开文件夹

### ISSUE THREAD

**Issue by hitlcl** [solosky/pixl.js#49]
当一个文件夹下包含 [3AZ] 01 - 8-bit Link (The Legend of Zelda).bin时，网页进入该文件夹会卡住（一直转圈）；在pixl打开该bin文件提示读取文件失败 且 无法删除。
复现流程：1、随便找一个amiibo的bin文件，重命名为[3AZ] 01 - 8-bit Link (The Legend of Zelda).bin
2、通过网页在根目录创建文件夹（名称为1），然后在该文件夹下上传重命名后的bin文件
3、网页打开 1 文件夹，会一直卡着转圈，pixl打开该文件提示读取文件失败。
4、pixl在文件夹列表长按，然后选择删除，无法删除文件

**Comment by solosky** [comment]
嗯，是个BUG，问题已经修复，在下一个版本发布。
如需验证可以使用最新的构建版本测试。
