### ISSUE TITLE
优化操作逻辑(建议)

### ISSUE THREAD

**Issue by tlb53257870** [solosky/pixl.js#59]
1）每次开机都要去选择文件，能不能记住上次的位置（卡片）
2）无限刷卡开关，是否可以单卡片记忆，或者默认开启
3）动画功能是否可以去掉隐藏（单纯做刷卡）
4）拥有唤醒功能，如果能默认上次选择的卡片或者设置默认卡片就好了与1）类似
5）能不能内部存储容量修改到设置菜单里面，去除菜单选项，直接进入文件夹
6）法律相关名称,是否可以修改为NTAG512

**Comment by tlb53257870** [comment]
NTAG215

**Comment by tlb53257870** [comment]
7）背光调节可否使用PWM调光 ，目前晚上还是太亮 ，能够调节亮度比较好

**Comment by solosky** [comment]
部分功能已经在实现中了，下一个版本会发布
