### ISSUE TITLE
外壳过紧

### ISSUE THREAD

**Issue by Liuzierjun** [solosky/pixl.js#60]
外壳拨轮开口处后方过紧，拨后无法回正，需要磨掉0.3-0.5mm

**Comment by solosky** [comment]
白橙大佬在修改新的壳子，敬请期待

**Comment by ca1e** [comment]
非程序或硬件问题

**Comment by Liuzierjun** [comment]
> 非程序或硬件问题

“项目由 白橙 大佬制作的外壳，可以在这里下载”
我没有其他方式联系或反馈该外壳问题，只能在此项目下反馈，而此外壳问题并未得到修复
