### ISSUE TITLE
2.5.0->2.5.1过程中不小心中断，一直卡在DFU模式

### ISSUE THREAD

**Issue by bytepoem** [solosky/pixl.js#69]
现在一直显示DFU Update Waiting...
拔插电池也还是显示这个

**Comment by rxvincent** [comment]
我也是这样，不知道怎么解决

**Comment by rxvincent** [comment]
用iNFC刷成功了，网页倒是一直都不行不知道为什么

**Comment by Minkey666** [comment]
我也是这样，到了这一步web就已经连不上了，用手机端可以刷，iNFC或者nfcConnect都可以

**Comment by bytepoem** [comment]
网页不稳定，建议通过app端操作
