### ISSUE TITLE
注释乱码

### ISSUE THREAD

**Issue by Ruach-yi** [solosky/pixl.js#74]
想研究一下显示驱动部分的代码，发现注释乱码 文件路径 ： fw/bootloader/src/lcd_drv.c

**Comment by ca1e** [comment]
@solosky 看一下本地编码是什么，已提交内容没法看了

**Comment by solosky** [comment]
文件注释我从源文件找回来了，你可以参考下。
另外这个屏幕的驱动芯片是ST7567，这个芯片网上资料很多，也可以问商家要驱动资料。
