### ISSUE TITLE
求助！传输文件完却没有文件在对应位置

### ISSUE THREAD

**Issue by Bosco1262** [solosky/pixl.js#76]
网页端与iOS端的infc都试过，每次传输文件显示完成后都没有对应文件，但是蓝牙连接应该是正常的。设置每次调完熄屏就没了。试过amiibolink功能可用，正常。固件最新版2.5.2，之前以为固件出bug，重刷固件能刷进，但没有改善问题，依然无法传输成功。想请教一下这种是属于硬件问题吗？我不是很懂

**Comment by Bosco1262** [comment]
好的

**Comment by solosky** [comment]
最近一周无回应，先关闭这个
