### ISSUE TITLE
藍芽模式

### ISSUE THREAD

**Issue by hankZZ111** [solosky/pixl.js#83]
針對在藍芽模式下不受系統設定休眠秒數之開關，否則某些時候在傳輸檔案時，常常因為休眠秒數到達而被迫切斷連線。

**Comment by solosky** [comment]
感谢提交，关于蓝牙传输超时问题参考 #81 ，后续版本会对这一块做一些功能优化。

**Comment by DanTheMan827** [comment]
I would suggest setting the auto-sleep value to nothing when bluetooth is connected, and restore the previous value once disconnected.

**Comment by solosky** [comment]
I will improve the ble connect timeout in next release.

**Comment by DanTheMan827** [comment]
@solosky I've written some code which I believe should work, although I can't seem to get it to compile.  Perhaps you know how to fix it.

https://github.com/DanTheMan827/pixl.js/commit/e2c447ffe3158ed26d83efc896789dd46c5cf3ca

The error given is `region RAM overflowed with stack`

**Comment by solosky** [comment]
Hi Dan, I would perfer to setup a long timeout value (e.g. 300s ) instead disable sleep timer.
