### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by Pocketmodster** [solosky/pixl.js#84]
Hello, how do I change the language on the device to English? Thank you

**Comment by Bosco1262** [comment]
I think you need to use another version

**Comment by solosky** [comment]
Sorry, Pixl.js doesn't have any other language translation for both firmware and web, it only supports Simplified Chinese. 

I will leave the issue open and may schedule English language support in future, but I am not promise it. 

Also, pull request is welcome if you are capable of translation for English, includes firmware, web and documentations.

**Comment by headhunter45** [comment]
It doesn't look like the code is setup for l10n yet. Do you have a plan or preference for how to set that up? I just started digging in, but I think I could setup something with a compile time define. I haven't looked too deep into how the settings work, but I can think of a few approaches for runtime language switching. I'm not sure on the web stuff though, maybe something similar, but I've been out of web dev for a few years now.

**Comment by solosky** [comment]
Since version 2.7.0 is offically support English language now, close this issue as completed. 
See #92 .
