### ISSUE TITLE
Uploads not working

### ISSUE THREAD

**Issue by Pocketmodster** [solosky/pixl.js#85]
Hello, please help I have an issue none of my uploads go through I only see this page and nothing else happens.
![Pixl-js](https://github.com/solosky/pixl.js/assets/95149143/416481b1-86cb-44fa-9056-350fdb15f846)

**Comment by solosky** [comment]
Would you please to press F12 and let me know the console output if you encountered same issue again?

For iOS device, we have iNFC app that fully support Pixl.js device, you can have a try. But we dont have any compatible app on Android platform, we may support Tagmo in future.

**Comment by solosky** [comment]
you can download the iNFC app by scan qrcode bellow,

![image](https://github.com/solosky/pixl.js/assets/480111/347d4e7c-ad53-457e-a817-312f3e9e4fd1)

**Comment by Pocketmodster** [comment]
Yes unfortunately on the website its not working still cant figure out why and f12 doesn't show anything it only controls my pc volume. I'm trying iNFC now but I would prefer the website because my amiibo files are on my pc just makes the process easier. Thanks again for your help in the matter.

**Comment by strengthen** [comment]
> Yes unfortunately on the website its not working still cant figure out why and f12 doesn't show anything it only controls my pc volume. I'm trying iNFC now but I would prefer the website because my amiibo files are on my pc just makes the process easier. Thanks again for your help in the matter.

You don't need to find Amiibo files by yourself, you can download 1026 Amiibo files directly by subscribing. It's more comprehensive than what's on your computer.
Subscribe link: https://raw.githubusercontent.com/strengthen/iNFCAmiibo/main/amiibo.infc
Video Tutorial 1: https://www.youtube.com/watch?v=X2NvyKzeaq8
Video Tutorial 2: https://www.youtube.com/watch?v=PNgcZlFqaJM

**Comment by Pocketmodster** [comment]
This is what I am currently using bought it on Amazon.![image](https://github.com/solosky/pixl.js/assets/95149143/bebaa779-106d-4987-9566-986cedf3c2ec)

**Comment by solosky** [comment]
The device looks great and should be compatible with the latest firmware. 
I just recorded a simple video to demonstrate how to upload amiibo bins to the device, hope it helps your out. 
One again, sorry we dont have english translation yet, but I think you can figure it out with online translator.

please let me know if you have more questions. 

https://github.com/solosky/pixl.js/assets/480111/bdaad278-9bae-4519-aa91-8378f8b114f0

**Comment by solosky** [comment]
Good news!
I have received an english version firmware contributed by @577fkj , though it is not build by latest code, it still worth have a try. 

[Pixl_EN_B35.zip](https://github.com/solosky/pixl.js/files/11748239/Pixl_EN_B35.zip)

**Comment by Pocketmodster** [comment]
Got it to work!! Thank you buddy and I appreciate all your help! I will keep the English file but I will continue to use your latest firmware file 2.6.0 since its newer. Thank you again

**Comment by Pocketmodster** [comment]
But I do hope whenever you release a new firmware that it can have multilanguage selection that would be awesome thanks again buddy!
