### ISSUE TITLE
v2.7.0 导致metadata里的notes无法正常显示

### ISSUE THREAD

**Issue by x-magic** [solosky/pixl.js#95]
当Amiibo文件在 [/fw/data/amiibo_data.csv](fw/data/amiibo_data.csv) 或通过网页端设置了元数据 notes 字段后，此字段会在调取Amiibo时显示在文件名及Amiibo名的下方。

此功能在v2.6.2时正常，但升级到v2.7.0后，通过网页端元数据设定的 notes 里的英文字符和部分符号就无法正常显示了，如：
`TPHD - 20 hearts` 会显示为 `(!T!P!H!D! !-! !2!0! !h!e!a!r!t!s!)!!`
![img1](https://github.com/solosky/pixl.js/assets/3180639/97cac5d3-39cf-418b-975d-115809012007)

`boxboy` 会显示为 `b?o?x?b?o?y??`
![img2](https://github.com/solosky/pixl.js/assets/3180639/486b8c2b-8d06-456f-bc6e-2de33932b0f4)

` ` （空格）会显示为 `@@` 或 `!!`
![img3](https://github.com/solosky/pixl.js/assets/3180639/ced57d23-a343-4813-84fa-d6d8af1df32f)

但中文的 notes 显示正常：

![img4](https://github.com/solosky/pixl.js/assets/3180639/bc093977-32f2-479c-bfeb-86b043d7e0c6)

这是[UTF-8的问题](https://github.com/solosky/pixl.js/blob/081f8f670ade1ae3032e38fe4b36d8cf7d7017c4/fw/application/src/app/amiibo/scene/amiibo_scene_amiibo_detail.c#L74)么？

此现象在任意系统语言设置都会出现

**Comment by solosky** [comment]
确认是个BUG，已经修复，下一个版本发布。
