### ISSUE TITLE
能否当作ntag215卡片模拟器使用

### ISSUE THREAD

**Issue by wolfshow** [solosky/pixl.js#98]
能否模拟多张ntag215 nfc卡存储在机器内使用？

**Comment by solosky** [comment]
现在就支持啊，把数据文件上传到Flash里面即可模拟。

**Comment by ca1e** [comment]
对不起，本设备主要功能为模拟amiibo，暂不提供其他模拟器功能

**Comment by wolfshow** [comment]
> 现在就支持啊，把数据文件上传到Flash里面即可模拟。 你可以试试，可能功能不是完全模拟NTG215的行为，有些命令没有实现。

能否当作215卡写入text record?

**Comment by solosky** [comment]
> > 现在就支持啊，把数据文件上传到Flash里面即可模拟。 你可以试试，可能功能不是完全模拟NTG215的行为，有些命令没有实现。
> 
> 能否当作215卡写入text record?

理论上行，你可以试试，不行再来提
